Feat: Add processing aiohttp StreamReader for proxying data from a request.
graphql-python/gql pull request #174
Opened 2020-11-26 11:46 UTC by anisov

When receiving a large file from a request(use aiohttp) and then transferring it through Graphql, it was necessary to read the data from the request and we can load it into RAM or save it to disk (to avoid memory leaks), and only after that it was possible to transfer it through graphql(use io.BytesIO or open()). In this branch, I tried to solved this problem.

2020-11-26 12:24 UTC, leszekhanusz commented
Thanks for your PR, that's definitely something I wanted to add.

Could you please:
* fix it so that the tests are passing if we do not use the aiohttp optional depency
* add docs on how to use it (new section in docs/usage/file_upload.rst). You can test the docs locally by running make docs

2020-11-26 13:01 UTC, leszekhanusz requested changes

2020-11-26 13:14 UTC, anisov commented on gql/transport/aiohttp.py
> +                variable_values, (aiohttp.StreamReader,)
ok, i do this in next commit

2020-11-26 13:15 UTC, anisov commented on gql/utils.py
> +def is_file_like(value: Any, additional_file_like_instances: Tuple[Any]) -> bool:
Ok, I will do it in the next commit

2020-11-26 13:47 UTC, anisov commented
I have embedded your suggestions into the code.

2020-11-26 16:55 UTC, leszekhanusz commented
Looks good!

What I would also like to integrate in this PR is the possibility to send large local files using an asynchronous generator as described [here](https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads).

Then we would need some test for those two functionalities.

2020-11-27 10:52 UTC, anisov commented
> Looks good!
> 
> What I would also like to integrate in this PR is the possibility to send large local files using an asynchronous generator as described [here](https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads).
> 
> Then we would need some test for those two functionalities.

Thanks, I'll do it on the weekend

2020-11-29 11:31 UTC, leszekhanusz commented
Very nice!

I just made some small modifications to the docs but cannot push it here.
Could you please check the box:
"Allow edits and access to secrets by maintainers"
Thanks

2020-11-29 19:27 UTC, anisov commented
> Very nice!
> 
> I just made some small modifications to the docs but cannot push it here.
> Could you please check the box:
> "Allow edits and access to secrets by maintainers"
> Thanks
Thanks! The checkbox in the "Allow maintainers to edit" field was already there, I rearranged it again. Or need to do something else?

2020-11-29 19:37 UTC, leszekhanusz commented
> Thanks! The checkbox in the "Allow maintainers to edit" field was already there, I rearranged it again. Or need to do something else?

It seems to work now... I've added my modifications.

2020-11-29 19:39 UTC, leszekhanusz approved these changes

2020-12-11 12:17 UTC, merged

2021-01-20 12:17 UTC, snowPu commented
When I try this
```
result = await client.execute(query, variable_values=params, upload_files=True)
```
 I get an error: `Object of type async_generator is not JSON serializable`