Add support for variable definitions in dsl
graphql-python/gql pull request #210
Opened 2021-05-21 02:37 UTC by wallee94

Hi all,

I was working in a small project and I needed a way to compose queries dynamically with variable definitions, so I can create the queries once depending on initial settings and just change the variables when sending them.
I created a `DSLVariableDefinitions` and `DSLVariable` class in the dsl module to add the option. I tried to make it similar to the current API :slightly_smiling_face: 

This is an example of how it works:

```python
var = DSLVariableDefinitions()
op = DSLMutation(
    ds.Mutation.createReview.args(review=var.review, episode=var.episode).select(
        ds.Review.stars, ds.Review.commentary
    )
)
op.variable_definitions = var
query = dsl_gql(op)
```

And it generates:

```graphql
mutation ($review: ReviewInput, $episode: Episode) {
  createReview(review: $review, episode: $episode) {
    stars
    commentary
  }
}
```

I have no experience with sphinx, please let me know if I need to adjust something.

2021-05-22 10:52 UTC, leszekhanusz commented
Thanks! I'll look into it.

2021-05-23 08:52 UTC, leszekhanusz commented
Your solution does not work with variables in input objects like this:

```
createReview(                                                                                                         
    review: {stars: $stars, commentary: $commentary}                                                                    
    episode: $episode                                                                                                   
  )
```

To solve this, the only way is to modify the recursive `ast_from_value` function from graphql-core.
As this function cannot be modified directly in graphql-core because it is a one-to-one copy of `astFromValue` from graphql-js
I made a copy paste inside gql. I agree that this is quite hackish.

graphql-js itself is currently in the process of changing quite a few things (See [graphql-js PR #3049](https://github.com/graphql/graphql-js/pull/3049)) and changing the `astFromValue` function to `ValueToLiteral`

I'll make an issue on graphql-js side to do this a little bit cleaner.

2021-05-23 23:44 UTC, wallee94 commented
Oh, you're right! I missed that option.

I agree that the only workaround is going to be copying the `ast_from_value` function. It is hackish but at the same time I think it makes sense to have a custom version of `ast_from_value` in the dsl module, because returning `VariableNodes` sounds very specific to composing a query.
It looks like `valueToLiteral` will add support for a `valueToLiteral` method in `GraphQLInputType`, but that wouldn't help because `DSLVariables` should work with any type

2021-05-24 16:02 UTC, leszekhanusz commented
Looks good!

I added some docs.

Now for the hard part, could you please add tests so that the code coverage stays at 100% ?

2021-05-24 21:30 UTC, wallee94 commented
Great! Thank you @leszekhanusz.
Sure, I'll work on the tests

2021-06-01 19:36 UTC, wallee94 commented
I added the tests and I think coverage is back to 100% again 🙂

2021-06-02 20:29 UTC, leszekhanusz requested changes
Great!

2021-06-02 20:29 UTC, leszekhanusz commented on gql/dsl.py
> +class DSLVariable:
Please add typing hints for all methods

2021-06-03 20:02 UTC, leszekhanusz approved these changes

2021-06-03 20:02 UTC, leszekhanusz commented
LGTM

2021-06-05 20:14 UTC, merged

2021-06-05 20:17 UTC, leszekhanusz commented
Thanks again for your PR!