Add HTTPX transport
graphql-python/gql pull request #370
Opened 2022-11-26 00:47 UTC by helderco

Fixes #154

This is an alternative to #340.

### Notes

- Both sync and async transports
- File upload support (but no stream or AsyncGenerator)
- Docs
- Sync tests based on requests tests
- Async tests based on aiohttp tests
- The other transports log the query and result in _info_ but I think it makes more sense for _debug_

Signed-off-by: Helder Correia

2022-11-26 11:59 UTC, helderco commented
I can't build docs:
```
docs run-test: commands[0] | sphinx-build -b html -nEW docs docs/_build/html
Traceback (most recent call last):
  File "/Users/helder/Projects/gql/.tox/docs/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/jinja2/__init__.py)
```

2022-11-26 13:28 UTC, leszekhanusz commented
Thanks a lot for your complete PR!

2022-11-26 13:30 UTC, leszekhanusz commented
> I can't build docs:
> 
> ```
> docs run-test: commands[0] | sphinx-build -b html -nEW docs docs/_build/html
> Traceback (most recent call last):
>   File "/Users/helder/Projects/gql/.tox/docs/bin/sphinx-build", line 5, in <module>
>     from sphinx.cmd.build import main
>   File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 25, in <module>
>     from sphinx.application import Sphinx
>   File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 43, in <module>
>     from sphinx.registry import SphinxComponentRegistry
>   File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/registry.py", line 24, in <module>
>     from sphinx.builders import Builder
>   File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 26, in <module>
>     from sphinx.util import import_object, logging, progress_message, rst, status_iterator
>   File "/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/sphinx/util/rst.py", line 21, in <module>
>     from jinja2 import Environment, environmentfilter
> ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/helder/Projects/gql/.tox/docs/lib/python3.8/site-packages/jinja2/__init__.py)
> ```

It's because of [this issue](https://github.com/sphinx-doc/sphinx/issues/10291).
As a workaround, you can run `pip install jinja2==3.0` and it should work.
I'll upgrade sphinx in a separate PR to fix this cleanly.

2022-11-26 13:34 UTC, helderco commented
Thanks, I was able to run locally and fixes already sent!

> I'll upgrade sphinx in a separate PR to fix this cleanly.

👍

2022-11-26 13:51 UTC, leszekhanusz requested changes
Please add the following changes:

- add httpx dependencies in `docs/intro.rst`
- add httpx link in `docs/usage/file_upload.rst`
- add a file in `docs/modules` for httpx and add it to `docs/modules/gql.rst` This should fix the non-working ref in the doc

Please don't use force-push but instead add a push a normal commit so that we can see the changes more easily.

2022-11-26 13:51 UTC, leszekhanusz commented on tests/test_httpx_online.py
> +async def test_aiohttp_simple_query(event_loop, protocol):
Please rename the test names in this file with httpx instead of aiohttp

2022-11-26 14:21 UTC, helderco commented
Do I add the `gql-with-httpx` to conda instructions in `intro.rst`? Where are those created?

2022-11-26 14:23 UTC, helderco commented
> Please don't use force-push but instead add a push a normal commit so that we can see the changes more easily.

Got it, but fyi, in Github you can see what changed with these buttons:

<img width="935" alt="Screen Shot 2022-11-26 at 13 22 18" src="https://user-images.githubusercontent.com/174525/204093608-8df1a94b-a50f-47f8-9112-77d85abea368.png">

At dagger we amend a lot to keep the history clean.

2022-11-26 14:26 UTC, leszekhanusz commented
> Do I add the `gql-with-httpx` to conda instructions in `intro.rst`? Where are those created?

In [another repository](https://github.com/conda-forge/gql-feedstock).
Maybe don't add it right now, I'll add it later with the next stable version of gql.

2022-11-26 14:32 UTC, leszekhanusz commented
> Got it, but fyi, in Github you can see what changed with these buttons:

:+1: 

> At dagger we amend a lot to keep the history clean.

I'm not a fan of force-pushing except in very rare occurrences.
The commits here are squashed anyway when we merge so the main history will still stay clean :smile:

2022-11-26 14:39 UTC, leszekhanusz approved these changes

2022-11-26 14:40 UTC, merged

2022-11-26 14:41 UTC, helderco commented
Thanks for the quick review and merge! 🎉

2022-11-26 14:45 UTC, leszekhanusz commented
> Thanks for the quick review and merge! tada

And thank you again for your help!

2022-12-16 15:08 UTC, prabhu commented
Any ideas when this would be released?

2022-12-16 16:52 UTC, leszekhanusz commented
@prabhu it's already released in a pre-release: [v3.5.0b0](https://github.com/graphql-python/gql/releases/tag/v3.5.0b0)